services:
  px4_ros2_allinone:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PX4_TAG: v1.16.1
    container_name: px4_ros2
    network_mode: bridge
    restart: unless-stopped
    environment:
      - DISPLAY=${DISPLAY}
      - QT_QPA_PLATFORM=xcb
      - FCU_URL=udp://:14540@127.0.0.1:14540
      - ROS_DOMAIN_ID=0
      - PX4_SIM_MODEL=gz_x500
      - LIBVA_DRIVER_NAME=
    ports:
      - "9090:9090"
      - "14540:14540/udp"
    volumes:
      - ./ws:/ws
      - ./Agents:/root/Agents
      - ./PX4-Autopilot:/opt/PX4-Autopilot
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/.Xauthority:/root/.Xauthority:ro
    devices:
      - /dev/dri:/dev/dri
    working_dir: /opt/PX4-Autopilot
    command: ["/usr/local/bin/container-startup.sh"]
